//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rivensoft.Mobile.MileageTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rivensoft.Mobile.MileageTracker.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage Tracker.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILEAGE TRACKER.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelApplicationBarIconText {
            get {
                return ResourceManager.GetString("CancelApplicationBarIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteApplicationBarIconText {
            get {
                return ResourceManager.GetString("DeleteApplicationBarIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOURNEY.
        /// </summary>
        public static string EditJourneyApplicationTitle {
            get {
                return ResourceManager.GetString("EditJourneyApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string EditJourneyDateLabel {
            get {
                return ResourceManager.GetString("EditJourneyDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END MILEAGE.
        /// </summary>
        public static string EditJourneyEndMileageLabel {
            get {
                return ResourceManager.GetString("EditJourneyEndMileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditJourneyPageTitle {
            get {
                return ResourceManager.GetString("EditJourneyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START MILEAGE.
        /// </summary>
        public static string EditJourneyStartMileageLabel {
            get {
                return ResourceManager.GetString("EditJourneyStartMileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire journeys after.
        /// </summary>
        public static string ExpireJourneysAfterSettingsLabel {
            get {
                return ResourceManager.GetString("ExpireJourneysAfterSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string NewApplicationBarIconText {
            get {
                return ResourceManager.GetString("NewApplicationBarIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOURNEY.
        /// </summary>
        public static string NewJourneyApplicationTitle {
            get {
                return ResourceManager.GetString("NewJourneyApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string NewJourneyDateLabel {
            get {
                return ResourceManager.GetString("NewJourneyDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END MILEAGE.
        /// </summary>
        public static string NewJourneyEndMileageLabel {
            get {
                return ResourceManager.GetString("NewJourneyEndMileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string NewJourneyPageTitle {
            get {
                return ResourceManager.GetString("NewJourneyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START MILEAGE.
        /// </summary>
        public static string NewJourneyStartMileageLabel {
            get {
                return ResourceManager.GetString("NewJourneyStartMileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to journeys.
        /// </summary>
        public static string PivotItemOneHeader {
            get {
                return ResourceManager.GetString("PivotItemOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveApplicationBarIconText {
            get {
                return ResourceManager.GetString("SaveApplicationBarIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsApplicationBarMenuItemText {
            get {
                return ResourceManager.GetString("SettingsApplicationBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitsSettingsLabel {
            get {
                return ResourceManager.GetString("UnitsSettingsLabel", resourceCulture);
            }
        }
    }
}
